openapi: 3.0.0
info:
  title: Sample API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: "1.0"
servers:
  - url: http://localhost:8080
    description: Local testing environment
paths:
  /rest/v1/ping:
    get:
      summary: Simple ping.
      tags:
        - ping
      responses:
        '200':
          description: Sample pong response
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/Pong"
    post:
      summary: Ping with an optional token.
      tags:
        - ping
      parameters:
          - name: token
            in: query
            required: false
            description: Token provided by the ping caller
            schema:
                type: string
                example: pong
      responses:
        '200':
          description: Sample pong response
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/Pong"
        '400':
          description: Validation error

components:
  schemas:
    Pong:
      type: object
      properties:
        timestamp:
          type: string
          format: date-time
          description: "Current timestamp"
        dt:
          type: string
          format: date
          description: "Test date"
        token:
          type: string
          example: "pong"
          description: "Ping token"
        token_type:
          type: string
          description: Response token type
          enum:
            - automatic
            - provided
